# Generated by Django 5.0.6 on 2026-05-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0003_lead_company_new_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campaignlead',
            name='campaigns_lead_unique_enrolment',
        ),
        migrations.RemoveConstraint(
            model_name='campaignstep',
            name='campaigns_step_unique_variant',
        ),
        migrations.AlterField(
            model_name='campaignlead',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=0, help_text='Last step number sent (0 = nothing sent yet)'),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='body_html_template',
            field=models.TextField(blank=True, help_text='HTML body. Use {{first_name}}, {{company}}, {{sender_name}}'),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='label',
            field=models.CharField(blank=True, help_text="Friendly name e.g. 'Initial outreach'", max_length=100),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='step_number',
            field=models.PositiveSmallIntegerField(help_text='Order of this step (1-based). Steps with the same number = A/B variants.'),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='subject_template',
            field=models.CharField(blank=True, help_text='Supports {{first_name}}, {{last_name}}, {{company}}, {{sender_name}}', max_length=300),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='task_description',
            field=models.TextField(blank=True, help_text='For LinkedIn/task steps: describe what the rep should do'),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='variant_label',
            field=models.CharField(default='A', help_text='A/B label — same step_number + different variant = split test', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='wait_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Days after previous step (step 1: days after enrollment)'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignlead',
            unique_together={('campaign', 'lead')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignstep',
            unique_together={('campaign', 'step_number', 'variant_label')},
        ),
    ]
