# Generated by Django 5.0.6 on 2026-06-11 12:40

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaignstep_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstep',
            name='wait_days',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(default=apps.campaigns.models.generate_campaign_name, max_length=200),
        ),
        migrations.AlterField(
            model_name='campaignlead',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaignsend',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('opened', 'Opened'), ('replied', 'Replied'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('bounced', 'Bounced')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='body_html_template',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='step_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='step_type',
            field=models.CharField(choices=[('email', 'Email'), ('linkedin', 'LinkedIn (manual)'), ('task', 'Task / Reminder')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='subject_template',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='task_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='variant_label',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Plain text or simple HTML. Use {{first_name}}, {{company}}, {{sender_name}}.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(help_text='Short label shown in template picker', max_length=100),
        ),
    ]
