# Generated by Django 5.0.6 on 2026-05-27 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight_type', models.CharField(choices=[('summary', 'Lead Summary'), ('next_action', 'Recommended Next Action'), ('risk', 'Risk Flag'), ('opportunity', 'Opportunity Signal')], max_length=20)),
                ('content', models.TextField()),
                ('model_version', models.CharField(max_length=50)),
                ('feedback', models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Not Useful'), ('ignored', 'Ignored')], help_text='User feedback on this insight. Powers model improvement.', max_length=10)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AILeadScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(help_text='Score from 0.0 to 100.0')),
                ('model_version', models.CharField(help_text="Model identifier. Example: 'gpt-4o-v1', 'rule-based-v2'", max_length=50)),
                ('factors', models.JSONField(blank=True, default=dict, help_text='Score breakdown by signal. Used for explainability.')),
            ],
            options={
                'db_table': 'ai_lead_scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
