# Generated by Django 5.0.6 on 2026-05-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_layer', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='aileadscore',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scores', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['lead', 'insight_type'], name='ai_insights_lead_id_0fe429_idx'),
        ),
        migrations.AddIndex(
            model_name='aileadscore',
            index=models.Index(fields=['lead', 'created_at'], name='ai_lead_sco_lead_id_2148b9_idx'),
        ),
    ]
