# Generated by Django 5.0.6 on 2026-05-27 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(help_text='When the action actually happened (can be back-dated).')),
                ('outcome', models.TextField(blank=True, help_text='Required for action types where requires_outcome=True (e.g. Cold Call result).')),
                ('bounce_detected', models.BooleanField(default=False, help_text='Set True for email actions where a bounce was received. Syncs to Lead.email_bounced via signal.')),
                ('dispatch_date', models.DateField(blank=True, help_text='For physical post actions: date the package was dispatched.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'actions',
                'ordering': ['performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('linkedin', 'LinkedIn'), ('email', 'Email'), ('phone', 'Phone / Call'), ('physical', 'Physical Post'), ('internal', 'Internal Note')], max_length=20)),
                ('requires_outcome', models.BooleanField(default=False, help_text='If True, the outcome field must be filled when logging this action.')),
                ('advances_stage', models.BooleanField(default=False, help_text='If True, logging this action may trigger a stage advancement check.')),
                ('icon', models.CharField(blank=True, help_text="Icon identifier for UI (e.g. 'linkedin', 'mail', 'phone').", max_length=50)),
            ],
            options={
                'db_table': 'action_types',
                'ordering': ['category', 'name'],
            },
        ),
    ]
