# Generated by Django 5.0.6 on 2026-05-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('leads', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='action',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='users.user'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='actions.actiontype'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['lead', 'performed_at'], name='actions_lead_id_b1ca5e_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['performed_by', 'performed_at'], name='actions_perform_331e30_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['action_type', 'performed_at'], name='actions_action__1337de_idx'),
        ),
    ]
