# Generated by Django 5.0.6 on 2026-05-27 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, help_text='Auto-populated from name. Used for dedup matching.', max_length=255)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_bounced', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin_url', models.URLField(blank=True)),
                ('linkedin_id', models.CharField(blank=True, db_index=True, help_text='LinkedIn numeric or username ID. Used for dedup.', max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('ai_score', models.FloatField(blank=True, help_text='Latest AI lead score (0-100). Sourced from AILeadScore history.', null=True)),
                ('raw_import_data', models.JSONField(blank=True, default=dict, help_text='Original row from import file. Never modified after insert.')),
                ('revive_after', models.DateField(blank=True, help_text='Date after which a dead lead can be re-engaged (default: 90 days).', null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('dead_at', models.DateTimeField(blank=True, null=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, help_text='Future multi-tenancy. Default to a single org UUID for now.', null=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadDuplicate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('email', 'Email Match'), ('linkedin', 'LinkedIn ID Match'), ('name_company', 'Name + Company Match'), ('semantic', 'Semantic / AI Match')], max_length=20)),
                ('confidence_score', models.FloatField(default=1.0, help_text='1.0 = exact match, <1.0 = fuzzy/AI match confidence.')),
                ('resolution', models.CharField(choices=[('pending', 'Pending Review'), ('merged', 'Merged into Primary'), ('kept_both', 'Kept Both Records'), ('ignored', 'Ignored / False Positive')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lead_duplicates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('database', 'Database / List'), ('manual', 'Manual Entry'), ('integration', 'API Integration')], max_length=20)),
                ('integration_config', models.JSONField(blank=True, default=dict, help_text='Phase 2: API config for automated ingestion. Leave empty for manual sources.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lead_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city_patterns', models.JSONField(default=list, help_text='List of city name substrings to match. Example: ["bangalore", "bengaluru"]')),
                ('action', models.CharField(choices=[('physical_post', 'Physical Post'), ('email_campaign', 'Email Campaign'), ('both', 'Both Channels')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = higher priority when multiple zones match.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'routing_zones',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('normalized_name', 'city'), name='unique_company_name_city_active'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.company'),
        ),
    ]
