# Generated by Django 5.0.6 on 2026-05-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0002_initial'),
        ('leads', '0001_initial'),
        ('pipeline', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='current_stage',
            field=models.ForeignKey(blank=True, help_text='Denormalized cache. Updated automatically by pipeline signal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_leads', to='pipeline.pipelinestage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='leadduplicate',
            name='duplicate_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_of', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadduplicate',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadduplicate',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_duplicates', to='users.user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadsource'),
        ),
        migrations.AddConstraint(
            model_name='leadduplicate',
            constraint=models.UniqueConstraint(fields=('lead', 'duplicate_lead'), name='unique_duplicate_pair'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leads_email_554d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['linkedin_id'], name='leads_linkedi_ae09d2_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['city'], name='leads_city_5fb92b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['current_stage', 'assigned_to'], name='leads_current_1ecbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['organization_id', 'current_stage'], name='leads_organiz_2e3e86_idx'),
        ),
    ]
