# Generated by Django 5.0.6 on 2026-05-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.automationrule'),
        ),
        migrations.AddConstraint(
            model_name='campaignlead',
            constraint=models.UniqueConstraint(fields=('campaign', 'lead'), name='unique_campaign_lead'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['rule', 'status'], name='webhook_log_rule_id_944493_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['lead', 'created_at'], name='webhook_log_lead_id_dfd8e1_idx'),
        ),
    ]
