# Generated by Django 5.0.6 on 2026-05-27 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the pipeline board. Lower = earlier.')),
                ('color', models.CharField(blank=True, help_text='Hex color code for UI display. Example: #4ade80', max_length=20)),
                ('is_terminal', models.BooleanField(default=False, help_text='Terminal stages (Dead, Bounced, Converted) cannot auto-advance.')),
                ('auto_advance_rules', models.JSONField(blank=True, default=dict, help_text='Phase 2: Rules for automatic stage advancement. Empty = manual only.')),
            ],
            options={
                'db_table': 'pipeline_stages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.TextField(blank=True, help_text='Optional context: why was this stage changed?')),
                ('auto_changed', models.BooleanField(default=False, help_text='True if changed by automation rule, False if changed by a human.')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_changes', to='users.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.lead')),
                ('from_stage', models.ForeignKey(blank=True, help_text='Null on the first transition (lead just created).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pipeline.pipelinestage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipeline.pipelinestage')),
            ],
            options={
                'db_table': 'lead_stage_history',
                'ordering': ['changed_at'],
                'indexes': [models.Index(fields=['lead', 'changed_at'], name='lead_stage__lead_id_81bce5_idx'), models.Index(fields=['changed_by', 'changed_at'], name='lead_stage__changed_33752d_idx')],
            },
        ),
    ]
