# Generated by Django 5.0.6 on 2026-05-27 19:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(help_text='Stored filename (server-side, sanitized).', max_length=255)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by the user.', max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('column_mapping', models.JSONField(default=dict, help_text='Map of {source_header: lead_field} used for this import.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.JSONField(default=list, help_text='List of row-level errors encountered during processing.')),
            ],
            options={
                'db_table': 'import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMappingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable name. Example: 'Apollo Standard Export'", max_length=100)),
                ('mapping', models.JSONField(default=dict, help_text='Map of {source_header: lead_field}.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping_templates', to='users.user')),
            ],
            options={
                'db_table': 'column_mapping_templates',
                'ordering': ['name'],
            },
        ),
    ]
