# Generated by Django 5.0.6 on 2026-05-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_leadfieldconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfieldconfig',
            name='detect_keywords',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of lowercase substrings for auto-detection. e.g. ["email","e-mail","mail"]'),
        ),
        migrations.AlterField(
            model_name='leadfieldconfig',
            name='display_label',
            field=models.CharField(help_text='Human-readable label shown in the mapping dropdown.', max_length=200),
        ),
        migrations.AlterField(
            model_name='leadfieldconfig',
            name='field_key',
            field=models.CharField(help_text="Programmatic key used in process_import(). Use '__' for related fields (e.g. company__name).", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='leadfieldconfig',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Display order in the mapping dropdown. Lower = higher up.'),
        ),
    ]
